# Generated by ariadne-codegen
# Source: graphql/queries.graphql

from typing import Any, List, Literal, Optional

from pydantic import Field

from .base_model import BaseModel


class ClosedOrMergedPullRequestsWithReviewComments(BaseModel):
    repository: Optional["ClosedOrMergedPullRequestsWithReviewCommentsRepository"]


class ClosedOrMergedPullRequestsWithReviewCommentsRepository(BaseModel):
    name: str
    pull_requests: (
        "ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequests"
    ) = Field(alias="pullRequests")


class ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequests(BaseModel):
    page_info: (
        "ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsPageInfo"
    ) = Field(alias="pageInfo")
    nodes: Optional[
        List[
            Optional[
                "ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodes"
            ]
        ]
    ]


class ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsPageInfo(
    BaseModel
):
    has_next_page: bool = Field(alias="hasNextPage")
    end_cursor: Optional[str] = Field(alias="endCursor")


class ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodes(
    BaseModel
):
    number: int
    title: str
    body: str
    url: Any
    head_ref_name: str = Field(alias="headRefName")
    author: Optional[
        "ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesAuthor"
    ]
    participants: "ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesParticipants"
    created_at: Any = Field(alias="createdAt")
    merged_at: Optional[Any] = Field(alias="mergedAt")
    closed_at: Optional[Any] = Field(alias="closedAt")
    comments: "ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesComments"
    review_threads: (
        "ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesReviewThreads"
    ) = Field(alias="reviewThreads")


class ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesAuthor(
    BaseModel
):
    typename__: Literal[
        "Actor", "Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"
    ] = Field(alias="__typename")
    login: str


class ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesParticipants(
    BaseModel
):
    page_info: (
        "ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesParticipantsPageInfo"
    ) = Field(alias="pageInfo")
    nodes: Optional[
        List[
            Optional[
                "ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesParticipantsNodes"
            ]
        ]
    ]


class ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesParticipantsPageInfo(
    BaseModel
):
    has_next_page: bool = Field(alias="hasNextPage")
    end_cursor: Optional[str] = Field(alias="endCursor")


class ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesParticipantsNodes(
    BaseModel
):
    login: str


class ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesComments(
    BaseModel
):
    page_info: (
        "ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesCommentsPageInfo"
    ) = Field(alias="pageInfo")
    nodes: Optional[
        List[
            Optional[
                "ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesCommentsNodes"
            ]
        ]
    ]


class ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesCommentsPageInfo(
    BaseModel
):
    has_next_page: bool = Field(alias="hasNextPage")
    end_cursor: Optional[str] = Field(alias="endCursor")


class ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesCommentsNodes(
    BaseModel
):
    author: Optional[
        "ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesCommentsNodesAuthor"
    ]
    created_at: Any = Field(alias="createdAt")
    updated_at: Any = Field(alias="updatedAt")
    body: str
    url: Any


class ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesCommentsNodesAuthor(
    BaseModel
):
    typename__: Literal[
        "Actor", "Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"
    ] = Field(alias="__typename")
    login: str


class ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesReviewThreads(
    BaseModel
):
    page_info: (
        "ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesReviewThreadsPageInfo"
    ) = Field(alias="pageInfo")
    nodes: Optional[
        List[
            Optional[
                "ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesReviewThreadsNodes"
            ]
        ]
    ]


class ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesReviewThreadsPageInfo(
    BaseModel
):
    has_next_page: bool = Field(alias="hasNextPage")
    end_cursor: Optional[str] = Field(alias="endCursor")


class ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesReviewThreadsNodes(
    BaseModel
):
    comments: "ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesReviewThreadsNodesComments"


class ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesReviewThreadsNodesComments(
    BaseModel
):
    nodes: Optional[
        List[
            Optional[
                "ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesReviewThreadsNodesCommentsNodes"
            ]
        ]
    ]


class ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesReviewThreadsNodesCommentsNodes(
    BaseModel
):
    author: Optional[
        "ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesReviewThreadsNodesCommentsNodesAuthor"
    ]
    created_at: Any = Field(alias="createdAt")
    updated_at: Any = Field(alias="updatedAt")
    body: str
    url: Any


class ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesReviewThreadsNodesCommentsNodesAuthor(
    BaseModel
):
    typename__: Literal[
        "Actor", "Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"
    ] = Field(alias="__typename")
    login: str


ClosedOrMergedPullRequestsWithReviewComments.model_rebuild()
ClosedOrMergedPullRequestsWithReviewCommentsRepository.model_rebuild()
ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequests.model_rebuild()
ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodes.model_rebuild()
ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesParticipants.model_rebuild()
ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesComments.model_rebuild()
ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesCommentsNodes.model_rebuild()
ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesReviewThreads.model_rebuild()
ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesReviewThreadsNodes.model_rebuild()
ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesReviewThreadsNodesComments.model_rebuild()
ClosedOrMergedPullRequestsWithReviewCommentsRepositoryPullRequestsNodesReviewThreadsNodesCommentsNodes.model_rebuild()
