[project]
name = "playground-github"
version = "0.0.1"
requires-python = ">=3.13.0"
dependencies = [
    "requests",
    "python-dotenv",
    "pygithub>=2.8.1",
]

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "ruff>=0.16.4",
    "pytest>=8.4.2",
]

[tool.uv.build-backend]
module-root = "src/playgroundgithub"

# PyTest
[tool.pytest.ini_options]
pythonpath = "src"
testpaths = [
    "tests"
]

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
