# Generated by ariadne-codegen
# Source: graphql/queries.graphql

from typing import Any, Dict, Optional, Union

from .async_base_client import AsyncBaseClient
from .base_model import UNSET, UnsetType
from .closed_or_merged_pull_requests_with_review_comments import (
    ClosedOrMergedPullRequestsWithReviewComments,
)
from .organisation_repositories import OrganisationRepositories


def gql(q: str) -> str:
    return q


class Client(AsyncBaseClient):
    async def organisation_repositories(
        self,
        org: str,
        after_repo: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any
    ) -> OrganisationRepositories:
        query = gql(
            """
            query OrganisationRepositories($org: String!, $afterRepo: String) {
              organization(login: $org) {
                repositories(
                  first: 100
                  after: $afterRepo
                  isArchived: false
                  orderBy: {field: UPDATED_AT, direction: DESC}
                ) {
                  pageInfo {
                    hasNextPage
                    endCursor
                  }
                  nodes {
                    name
                    isPrivate
                    createdAt
                    updatedAt
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"org": org, "afterRepo": after_repo}
        response = await self.execute(
            query=query,
            operation_name="OrganisationRepositories",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return OrganisationRepositories.model_validate(data)

    async def closed_or_merged_pull_requests_with_review_comments(
        self,
        owner: str,
        name: str,
        after_pr: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any
    ) -> ClosedOrMergedPullRequestsWithReviewComments:
        query = gql(
            """
            query ClosedOrMergedPullRequestsWithReviewComments($owner: String!, $name: String!, $afterPR: String) {
              repository(owner: $owner, name: $name) {
                name
                pullRequests(
                  first: 50
                  after: $afterPR
                  baseRefName: "develop"
                  states: [CLOSED, MERGED]
                  orderBy: {field: UPDATED_AT, direction: DESC}
                ) {
                  pageInfo {
                    hasNextPage
                    endCursor
                  }
                  nodes {
                    number
                    title
                    body
                    url
                    headRefName
                    author {
                      __typename
                      login
                    }
                    participants(first: 10) {
                      pageInfo {
                        hasNextPage
                        endCursor
                      }
                      nodes {
                        login
                      }
                    }
                    createdAt
                    mergedAt
                    closedAt
                    comments(first: 50) {
                      pageInfo {
                        hasNextPage
                        endCursor
                      }
                      nodes {
                        author {
                          __typename
                          login
                        }
                        createdAt
                        updatedAt
                        body
                        url
                      }
                    }
                    reviewThreads(first: 50) {
                      pageInfo {
                        hasNextPage
                        endCursor
                      }
                      nodes {
                        comments(first: 50) {
                          nodes {
                            author {
                              __typename
                              login
                            }
                            createdAt
                            updatedAt
                            body
                            url
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "owner": owner,
            "name": name,
            "afterPR": after_pr,
        }
        response = await self.execute(
            query=query,
            operation_name="ClosedOrMergedPullRequestsWithReviewComments",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return ClosedOrMergedPullRequestsWithReviewComments.model_validate(data)
