# Generated by ariadne-codegen
# Source: graphql/queries.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class OrganisationRepositories(BaseModel):
    organization: Optional["OrganisationRepositoriesOrganization"]


class OrganisationRepositoriesOrganization(BaseModel):
    repositories: "OrganisationRepositoriesOrganizationRepositories"


class OrganisationRepositoriesOrganizationRepositories(BaseModel):
    page_info: "OrganisationRepositoriesOrganizationRepositoriesPageInfo" = Field(
        alias="pageInfo"
    )
    nodes: Optional[
        List[Optional["OrganisationRepositoriesOrganizationRepositoriesNodes"]]
    ]


class OrganisationRepositoriesOrganizationRepositoriesPageInfo(BaseModel):
    has_next_page: bool = Field(alias="hasNextPage")
    end_cursor: Optional[str] = Field(alias="endCursor")


class OrganisationRepositoriesOrganizationRepositoriesNodes(BaseModel):
    name: str
    is_private: bool = Field(alias="isPrivate")
    created_at: Any = Field(alias="createdAt")
    updated_at: Any = Field(alias="updatedAt")


OrganisationRepositories.model_rebuild()
OrganisationRepositoriesOrganization.model_rebuild()
OrganisationRepositoriesOrganizationRepositories.model_rebuild()
